### Mostrar la pagina de inicio
GET http://localhost:3008

### Mostrar todos los accesorios
GET http://localhost:3008/computacion

### Mostrar accesorio por categoria
GET http://localhost:3008/computacion?categoria=Accesorios

### Mostrar un accesorio por su id
GET http://localhost:3008/computacion/6674b8f3690515eecf9a08ad

### Filtar un accesorio por su nombre
GET http://localhost:3008/computacion/nombre/la

### Agregar un nuevo producto
POST http://localhost:3008/computacion/
Authorization: ####agregar tu token######
content-type: application/json

{
    "codigo": 77,
    "nombre": "Nuevo Producto",
    "precio": 1000,
    "categoria": "Smartphone"
   
}
### Modificar/Actualizar un producto parcialmente
PATCH http://localhost:3008/computacion/6674b8f3690515eecf9a08b6
Authorization: ####agregar tu token######
content-type: application/json

{
    "precio": 200000
}

### Eliminar un producto
DELETE http://localhost:3008/computacion/66761b38d32f37e2968f3179
Authorization: ####agregar tu token######

### Login y obtener token
POST http://localhost:3008/login
Content-Type: application/json

{
    "username": "username",
    "password": "password"
}
