### Mostrar la pagina de inicio
GET http://localhost:3008
### Mostrar todos los accesorios

GET http://localhost:3008/computacion
### Mostrar un accesorio

GET http://localhost:3008/computacion/6674b8f3690515eecf9a08ae
### filtar un accesorio por su nombre

GET http://localhost:3008/computacion/nombre/la

### Agregar un nuevo producto
POST http://localhost:3008/computacion/
content-type: application/json

{
    "codigo": 55,
    "nombre": "Nuevo Producto",
    "precio": 50000,
    "categoria": "Smartphone"
   
}
### Modificar/Actualizar un producto parcialmente
PATCH http://localhost:3008/computacion/6674b8f3690515eecf9a08b6
content-type: application/json

{
    "precio": 200000
}
