### Mostrar la pagina de inicio
GET http://localhost:3008
### Mostrar todos los accesorios

GET http://localhost:3008/computacion
### Mostrar un accesorio

GET http://localhost:3008/computacion/6674b8f3690515eecf9a08ae
### Borrar un accesorio

